version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: claimprocess
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
  fastapi:
    build:
      context: .
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: claimprocess
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      API_KEY: ${API_KEY}
      PAYMENT_GATEWAY_ENDPOINT: ${PAYMENT_GATEWAY_ENDPOINT}
      PAYMENT_GATEWAY_KEY: ${PAYMENT_GATEWAY_KEY}
    ports:
      - '8000:8000'
volumes:
  postgres_data:
  redis_data: